---
- name: Verify
  hosts: all
  become: true
  tasks:
    - name: Gather installed package facts.
      ansible.builtin.package_facts:
        manager: auto

    - name: Assert amazon-ssm-agent is installed.
      ansible.builtin.assert:
        that:
          - "'amazon-ssm-agent' in ansible_facts.packages"
        fail_msg: amazon-ssm-agent package is not installed.

    - name: Stat the SSM agent configuration directory.
      ansible.builtin.stat:
        path: /etc/amazon/ssm
      register: aws_ssm_conf_dir

    - name: Assert the SSM agent configuration directory exists.
      ansible.builtin.assert:
        that:
          - aws_ssm_conf_dir.stat.exists
          - aws_ssm_conf_dir.stat.isdir
        fail_msg: /etc/amazon/ssm does not exist.

    - name: Stat the amazon-ssm-agent binary.
      ansible.builtin.stat:
        path: /usr/bin/amazon-ssm-agent
      register: aws_ssm_binary

    - name: Assert the amazon-ssm-agent binary is installed and executable.
      ansible.builtin.assert:
        that:
          - aws_ssm_binary.stat.exists
          - aws_ssm_binary.stat.mode == '0755'
        fail_msg: /usr/bin/amazon-ssm-agent is missing or not mode 0755.
